# Use Java 17 base image

FROM eclipse-temurin:17-jdk-alpine

# Set workdir inside container
WORKDIR /app

# Copy jar built locally
COPY target/01-back-0.0.1-SNAPSHOT.jar app.jar

# Expose port (matches container port in docker-compose)
EXPOSE 8088

# Run Spring Boot jar
ENTRYPOINT ["java","-jar","app.jar"]
