# Build stage: Use Node.js to build the Angular app
# Use Node.js 20 Alpine image for a lightweight build environment
FROM node:20-alpine as build
# Set working directory and enter to it
WORKDIR /app
# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./
# Install dependencies with legacy peer deps to avoid conflicts
RUN npm install --legacy-peer-deps
# Copy the rest of the application code
COPY . .
# Build the Angular app for production
# this transpiles TypeScript to JavaScript , bundles and minifies the code
# and outputs the static files to the dist/01-front/browser directory
RUN npm run build

# nginx is a lightweight web server used to serve static files , faster than a Node server cuz it's written in C
# it support high concurrency and low memory usage 
# Nginx has built-in tools for compression (gzip), caching headers
# and SSL handling that are harder to configure manually in a simple Node server
FROM nginx:alpine

# Copy the custom nginx config to replace the default one
# this config handles routing for Angular's client-side routing cuz by default nginx tries to find files on the server
# which doesn't work with SPAs , so we redirect all requests to index.html
COPY nginx.conf /etc/nginx/conf.d/default.conf   

# Copy built Angular app from the build stage to nginx html directory
# the /usr/share/nginx/html is the default directory where nginx serves static files from
# so we copy our built files there , so now nginx can serve our Angular app
COPY --from=build /app/dist/01-front/browser /usr/share/nginx/html

# Expose port 80 to match nginx default port
# this line is optional cuz nginx already listens on port 80 by default and we can specify port mapping when running the container
EXPOSE 80