FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

FROM nginx:alpine

# Copy the custom nginx config to replace the default one
COPY nginx.conf /etc/nginx/conf.d/default.conf   

# Copy the Angular build files
COPY --from=build /app/dist/01-front/browser /usr/share/nginx/html

EXPOSE 80